Resources:
  gamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.GAMES_TABLE}
      AttributeDefinitions:
        - AttributeName: gameID
          AttributeType: S
        - AttributeName: createTime
          AttributeType: N
      KeySchema:
        - AttributeName: gameID
          KeyType: HASH
        - AttributeName: createTime
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  movesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.MOVES_TABLE}
      AttributeDefinitions:
        - AttributeName: gameID
          AttributeType: S
      KeySchema:
        - AttributeName: gameID
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  connTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.CONN_TABLE}
      AttributeDefinitions:
        - AttributeName: connID
          AttributeType: S
        - AttributeName: gameID
          AttributeType: S
      KeySchema:
        - AttributeName: connID
          KeyType: HASH
        - AttributeName: gameID
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 4
        WriteCapacityUnits: 4
      GlobalSecondaryIndexes:
        - IndexName: gameIDIndex
          KeySchema:
            - AttributeName: gameID
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 4
            WriteCapacityUnits: 4

