Resources:

  IncanGoldGamesRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: incangold-games-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              # we give access to the Lambda and Lambda@Edge service to assume our role
              Service:
                - lambda.amazonaws.com
                - edgelambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole




